# Generated by Django 3.0.7 on 2020-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200907_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='positions',
            field=models.CharField(default='member', max_length=200),
        ),
    ]
